server:
  port: 80

spring:
  application:
    name: happy_station_eureka

eureka:
  client:
    service-url:
      defautZone: http://localhost:8761/eureka
    fetch-registry: true  #允许拉取注册信息
    register-with-eureka: true  #允许注册到别的eureka上
